### PR TITLE
feat(contribution-types): added "Data" contribution

### PR DESCRIPTION
**Pull request by smoia**
What:
Implements the "Data" category from all-contributors/all-contributors#336

Why:
Cf. all-contributors/all-contributors#334

How:
Used #176 as a blueprint

**Checklist**:

- [x] Documentation
- [x] Tests
- [x] Ready to be merged 
- [ ] Added myself to contributors table

### CODE REVIEW

**Comment by smoia** [comment]
I saw that the latest PRs have all validation issues - is it ok or should I change something?

**Comment by Berkmann18** [comment]
@smoia You indeed to make sure the tests pass (cf. https://circleci.com/gh/all-contributors/all-contributors-cli/865?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link), I briefly looked at the error which states that a module is missing.
Make sure the test passes locally.

**Comment by Berkmann18** [comment]
Let us know if you need help.

**Comment by smoia** [comment]
Ok, sorry it took me so long!
The problem was that node and yarn were outdated - hence the failing of the tests.
I updated required yarn and node.

**Comment by Berkmann18** [comment]
@all-contributors please add @smoia for code

**Comment by Berkmann18** [comment]
@smoia It's fine!

**Pull request merged**
