### PR TITLE
feat: Pretty-print the generagted HTML table

### LINKED ISSUE #189: Pretty-print/Format the generated HTML table
- `all-contributors-cli` version: N/A
- `node` version: N/A
- `npm` (or `yarn`) version: N/A

What you did:
Enjoyed the bot adding/creating the HTML table

What happened:
The diffs for the HTML table are difficult to parse since they are all on one line

Reproduction repository:
https://github.com/entropic-dev/entropic/pull/179/files

Problem description:
The HTML table currently is  emmitted as a single line, that makes a diff hard to read, compared to the json file

Suggested solution:
"Pretty Print" the table code so the elements are on separate lines (and possibly indented).
I would also assume this is better git-blob wise since it is a smaller amount of data if 2-3 short lines change vs 1 very long line (this is a guess).

### PR DESCRIPTION
**Pull request by nschonni**
Closes #189
Keeps the Table left aligned, and moves the tr and td in by 2 spaces each

### CODE REVIEW

**Comment by jakebolam** [comment]
Thanks 🙏 @nschonni

**Comment by jakebolam** [comment]
@all-contributors please add @nschonni for code

**Comment by nschonni** [comment]
Thanks @Berkmann18!
Is there a process for getting the bot updated too? Or does the lockfile there need to be manually updated https://github.com/all-contributors/all-contributors-bot/blob/master/yarn.lock

**Comment by Berkmann18** [comment]
@nschonni It depends on the changes as some may only need to be done on the CLI for it to be used by the bot (I believe that's one of them) and others which would require some changes on the bot as well.

In the case of lock file updates, it would have to be done there as well.

**Pull request merged**
