### PR TITLE
feat: display a meaningful error when the config file is missing

### PR DESCRIPTION
**Pull request by darekkay**
## What

When you try to add a user with `.all-contributorsrc` missing, you will get a cryptic error message (see also all-contributors/all-contributors#378):

```
$ all-contributors add darekkay maintenance
Cannot read property 'then' of null
```

This PR displays a meaningful error message in this case.

## Why

So users know what's causing the problem.

## How

Before a contribution is being added, the script checks whether the config file exists. If it doesn't, an error message is being displayed:

```
$ all-contributors add darekkay maintenance
Configuration file not found: C:\projects\test\.all-contributorsrc
```

**Checklist**:

- [ ] Documentation N.A.
- [ ] Tests (the cli doesn't have any tests)
- [x] Ready to be merged 
- [x] Added myself to contributors table

### CODE REVIEW

**Review by Berkmann18 — CHANGES_REQUESTED** [review]
Would it be possible to add/update tests?

**Comment by darekkay** [comment]
The ESlint warning is not caused by this PR. I've fixed it in a separate PR: #289

> Would it be possible to add/update tests?

There are no tests for the whole `cli.js` file. And I get why - because testing `addContribution` on its own probably isn't easy. If a missing test for an untested file is blocking this PR from being merged, feel free to close it (or leave it open for someone else to pick up).

**Comment by Berkmann18** [comment]
> There are no tests for the whole cli.js file. And I get why - because testing addContribution on its own probably isn't easy. If a missing test for an untested file is blocking this PR from being merged, feel free to close it (or leave it open for someone else to pick up).

That's a good point CLI E2E tests can be very tricky to do.

**Comment by Berkmann18** [comment]
> There are no tests for the whole cli.js file. And I get why - because testing addContribution on its own probably isn't easy. If a missing test for an untested file is blocking this PR from being merged, feel free to close it (or leave it open for someone else to pick up).

That's a good point CLI E2E tests can be very tricky to do.

**Review by Berkmann18 — APPROVED** [review]

**Pull request merged**
