### PR TITLE
feat: Auto discover contributors

### PR DESCRIPTION
**Pull request by mrchief**
**What**: Way to auto discover contributors based on heuristics

**Why**: See the discussion at https://github.com/all-contributors/all-contributors-cli/issues/117 and https://github.com/all-contributors/all-contributors-cli/issues/175

**How**: A new command `discover` is defined to initiate the process. It queries issues list for a given repo and based on predefined criteria, tries to determine contributor and their type(s) of contribution.

**Checklist**:

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged 
- [ ] Added myself to contributors table 

Visit https://github.com/all-contributors/all-contributors-cli/issues/117#issuecomment-491557557 to see this in action.

### CODE REVIEW

**Comment by mrchief** [comment]
It's a WIP but I wanted to put it up to get early feedback. I see a few todos:

 - add some more tests
 - define a new command and hook this up
 - integrate with `src/repo/github.getUserInfo` to get complete user profile info
 - provide a way for users to define their own label patterns (#175) - this could be a separate PR though.

Let me know if this sounds OK to you all.

**Comment by jakebolam** [comment]
Looks awesome @Berkmann18 is leading this effort. I'll defer to him

**Comment by mrchief** [comment]
>Feel free to check out the nyc /ml  branches which I've been working on, and the ac-learn repo.

The `ml` branch seems to 404 out for me. But I checked out `nyc` branch and `ac-learn` repo. The `ml` approach looks good towards solving #175 in a much more comprehensive way. 

My branch seems to be at the very starting point of [nyc comapre](https://github.com/all-contributors/all-contributors-cli/compare/nyc). The approaches seem similar except that you're way ahead about discovering categories and handling edge cases. 

At this point, I don't see any point in continuing my PR. I'm gonna close it and wait for you to finish your work.

**Comment by Berkmann18** [comment]
> The `ml` branch seems to 404 out for me.

Well spotted, I didn't push that on the remote, but now it should be visible.
The only difference between both branches (`nyc`/`ml`) is that `ml` is not using the category matcher function you can find in the `./src/findCategory` in the `nyc` branch.

> My branch seems to be at the very starting point of nyc comapre. The approaches seem similar except that you're way ahead about discovering categories and handling edge cases.

Well, our discussion and the diagrams I made and shared on the slack channel including some issues like [this NYC one](https://github.com/mntnr/name-your-contributors/issues/45) drive this up (so you definitely helped 😁).

> At this point, I don't see any point in continuing my PR. I'm gonna close it and wait for you to finish your work.

I'm more than happy for you to contribute to either branch (or even `ac-learn` for that matter), especially as you seem to have the same plan regarding the auto fetching.
And as you may have noticed both the `nyc` branch (and the `ml` to an extent) haven't been updated in the last few days and that's because I had some stuff to do (comps and such; hence me not being responsive the past 72h) and I'm trying to get `ac-learn` (_which is yet to be published and implemented in this CLI_) to a satisfactory point to resume the work on [what I laid out](https://github.com/all-contributors/all-contributors-cli/blob/ml/src/cli.js#L184-L187).

**Comment by mrchief** [comment]
> to a satisfactory point to resume the work on what I laid out .

Couldn't get the draw.io diagram to open. Gonna try again in a incognito window.  

> If you have any questions/doubts/issues/suggestions/ideas, feel free to comment on relevant issues, on slack, discord or email and I'll do my best to reply in a timely fashion 😄.

Can you send me an invite to slack or discord? 

> I'm more than happy for you to contribute to either branch (or even ac-learn for that matter), especially as you seem to have the same plan regarding the auto fetching.

Yeah, would love to contribute. There is a quite bit of catch up for me to do though (although part of me fears that you might be done with it before I can do that 😄).

**Comment by Berkmann18** [comment]
@mrchief 
> Couldn't get the draw.io diagram to open. Gonna try again in a incognito window.

Here' are the links
- category graph: https://drive.google.com/file/d/1uL9saIuZl3rj8sOo9xsLOPByAe28qhwa/view?usp=sharing
- AC/NYC: https://drive.google.com/file/d/1oC1AsQMbyipLRdhLbvE1nmHodcuDmftY/view?usp=sharing

> Can you send me an invite to slack or discord?

[Here it is](https://join.slack.com/t/all-contributors/shared_invite/enQtNTE3ODMyMTA4NTk0LTUwZDMxZGZkMmViMzYzYzk2YTM2NjRkZGM5Yzc0ZTc5NmYzNWY3Y2Q0ZTY3ZmFhZDgyY2E3ZmIzNWQwMTUxZmE).

> Yeah, would love to contribute.

Sweet.

> There is a quite bit of catch up for me to do though (although part of me fears that you might be done with it before I can do that 😄).

That's fine and I doubt I'll finish the whole feature for every contribution types (or even 24/27) on my own for a good month.

**Comment by tenshiAMD** [comment]
Related to https://github.com/all-contributors/cli/issues/88

**Pull request closed without merging**
