### PR TITLE
feat: suggest matching commands if the user mistypes 

### PR DESCRIPTION
**Pull request by jamesgeorge007**
This PR introduces a simple enhancement so as to have a suitable message which shows up if the user makes a typo. 

**Checklist**:

- [ ] Documentation
- [x] Tests
- [x] Ready to be merged 
- [ ] Added myself to contributors table

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
@jakebolam @jfmengels Thoughts :thinking:

**Comment by jakebolam** [comment]
@jamesgeorge007 love it <3

**Comment by jamesgeorge007** [comment]
@jakebolam May I know the reason behind keeping this on hold :thinking:

**Comment by jakebolam** [comment]
Thanks for this @jamesgeorge007 looks great!

**Comment by jamesgeorge007** [comment]
@allcontributors[bot] please add jamesgeorge007 for code.

**Pull request merged**
