### PR TITLE
feat: support Github Enterprise

### PR DESCRIPTION
**Pull request by hipstersmoothie**
**What**:

* add isEnterprise config option
* add function to change hostname if isEnterprise true

depends private key implemented in #95 

**Why**:

I'd like to generate all-contributors for my github enterprise projects.

**How**:

Adding a new config option.

**Checklist**:

- [x] Documentation
- [x] Tests
- [x] Ready to be merged 
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by hipstersmoothie** [comment]
I'm trying to add myself as a contributor at work but the rate limit has been hit. How can i change this?

**Comment by hipstersmoothie** [comment]
I VPNed into my home and the commands worked. But there doesn't seem to be any docs saying what to do when you see the rate limit.

**Comment by hipstersmoothie** [comment]
Waiting to update until #95 merged cause we changed the same lines

**Comment by chinesedfan** [comment]
@hipstersmoothie Friendly ping to tell you that #95 has been merged.

**Comment by jakebolam** [comment]
@hipstersmoothie I ran into the rate limit too: I've opened the issue #121, and put up a basic PR on this too #122

**Comment by Berkmann18** [comment]
@hipstersmoothie Do you still have the time to work on this?

**Comment by Berkmann18** [comment]
Friendly ping @hipstersmoothie .

**Comment by amaltson** [comment]
Any chance this will be looked at again? Would love to use it at work too!

**Comment by Berkmann18** [comment]
@amaltson Well, @hipstersmoothie doesn't seem to have the time to finish this so it's up for anyone who wants to work on this feature.

**Comment by tylerkrupicka** [comment]
I'm working with @hipstersmoothie to get this branch updated!

**Comment by adierkens** [comment]
Can we get this merged and released?

**Comment by amaltson** [comment]
Yes please! Would love to see this go in 😄

**Comment by hipstersmoothie** [comment]
Woo boo!

**Pull request merged**
